- name: Copyng nginx.conf
  copy: 
    src: files/nginx.conf
    dest: "{{ nginx_conf_path }}"
    mode: 0644
    owner: root
    group: root
    backup: true

- name: Copyng conf.d
  copy: 
    src: files/conf.d/
    dest: /etc/nginx/conf.d 
    mode: 0644
    owner: root
    group: root

- name: Copyng certs
  copy:
    src: files/certs/
    dest: /etc/nginx/certs
    mode: 0640
    owner: root
    group: nginx

- name: Creating log file
  file: 
    path: "{{ item }}"
    state: touch
    mode: 0644
    owner: nginx
    group: adm
    modification_time: preserve
    access_time: preserve
  loop:
    - "/var/log/nginx/{{ site_name }}.error.log"
    - "/var/log/nginx/{{ site_name }}.access.log"

- name: Copyng site config
  template:
    src: "{{ site_template }}"
    dest: /etc/nginx/vhosts/{{ site_name }}.conf
    mode: 0644
    owner: root
    group: root

- name: Copying upstream config
  template:
    src: upstream.conf.j2
    dest: /etc/nginx/conf.d/upstream.conf
