- name: Add Nginx repo with latest versions
  copy: 
    src=files/rhel8.repo 
    dest=/etc/yum.repos.d/nginx.repo 
    mode=0644
    owner=root
    group=root

- name: Install nginx
  dnf:
    name: nginx
    enablerepo: nginx-mainline
    state: latest
  register: nginx_update

- import_tasks: modules.yml
  tags: build
  when: nginx_update.changed

- include_tasks: certbot.yml
  when: subdomain and issue_certs

- include_tasks: configs.yml

- include_tasks: subdomain.yml

- name: Verify Nginx config
  command: nginx -t
  changed_when: false

- name: Enabling nginx service
  service:
    name: nginx
    state: started
    enabled: true
