- name: Add Nginx repo with latest versions
  copy: 
    src=files/rhel8.repo 
    dest=/etc/yum.repos.d/nginx.repo 
    mode=644
    owner=root
    group=root

- name: Install nginx
  dnf:
    name: nginx
    enablerepo: nginx-mainline
    state: latest

- import_tasks: modules.yml

- import_tasks: configs.yml
  when: update_configs | default('false')

- import_tasks: certbot.yml
  when: subdomain and issue_certs

- import_tasks: subdomain.yml

- name: Enabling nginx service
  service:
    name: nginx
    enabled: true
