- name: Creating subdomain directories
  file: 
    path: "/home/{{ site_user_name }}/www/{{ item.name }}"
    state: directory
    owner: "{{ site_user_name }}"
    group: "{{ site_user_name }}"
    mode: 0755
  loop: "{{ subdomain }}"

- name: Copyng site config
  template:
    src: "{{ item.template }}"
    dest: "/etc/nginx/vhosts/{{ item.name }}.conf"
    mode: 0644
    owner: root
    group: root
  loop: "{{ subdomain }}"
