- hosts: web
  become: yes

  vars:
    - admin_user: "support"
    - site_user_name: "aquatherm"
        
  roles:
      # add ssh and firewall role:
      #   create sftp users
      #   sshd_config for secure  and sftp
    - role: common
    - role: nginx
      vars: 
        - issue_certs: false
        - site_name: "aquatherm72.ru"
        - tmp_site_name: "test.aquatherm72.ru"
        - site_template: presta.conf.j2
        - subdomain:
          - { name: "dev", template: "subd_presta.conf.j2", php_version: "php73" }
        
    - role: mysql
      tags: mysql
    - role: php
      tags: php
      vars:
        - system_php: "7.4"  # system php only 7.2,7.3,7.4,8.0,8.1
        - reinstall_php: false
        - secondary_php:     # can choose from 5.6 to 8.1
          - name: php73
            install: true
    - role: backup
      vars:
        - email: "alpi@keemail.me"
      tags: backup
      # copy crontask 
