- name: Create backup dir
  file:
    path: "/home/{{ site_user_name }}/backup/{{ site_name }}"
    state: directory
    mode: 0750
    owner: "{{ site_user_name }}"
    group: "{{ site_user_name }}"

- name: Copy drive client
  copy:
    src: drive
    dest: "/home/{{ site_user_name }}/backup"
    mode: 0750
    owner: "{{ site_user_name }}"
    group: "{{ site_user_name }}"

- name: Install backup script
  template: 
    src: backup.sh.j2
    dest:  "/home/{{ site_user_name }}/backup/backup.sh"
    owner: "{{ site_user_name }}"
    group: "{{ site_user_name }}"
