  - name: disable default MariaDB module
    copy:
      dest: /etc/dnf/modules.d/mysql.module
      content: |
        [mysql]
        name=mysql
        stream=10.5
        profiles=server
        state=enabled

- name: Install Mariadb from RHEL Library
  dnf:
    name: @mariadb
    state: present

- name: Enable and start MariaDB
  service:
    name: mariadb
    state: started
    enabled: yes
