- name: Create pma_tmp file variable
  set_fact:
    pma_tmp: /tmp/pma_link.txt
    blowfish_secret: "{{ lookup('password','/dev/null chars=ascii_letters,digits length=32') }}"

- name: Get phpmyadmin URL
  shell: 
    cmd: "wget https://www.phpmyadmin.net/home_page/version.txt -q -O- > {{ pma_tmp }}"
    warn: false
  args:
    creates: "{{ pma_tmp }}"

- name: Get version
  shell: "cat {{ pma_tmp }} | cut -d '\n' -f 1"
  register: pma_version
  changed_when: false

- name: Get URL
  shell: "cat {{ pma_tmp }} | cut -d '\n' -f 3"
  register: pma_url
  changed_when: false

- name: Download latest phpmyadmin 
  unarchive:
    src: "{{ pma_url.stdout }}"    
    dest: /opt
    remote_src: yes
  register: pma_source

- name: Extract files
  copy:
    src: "{{ pma_source.dest }}/phpMyAdmin-{{ pma_version.stdout }}-all-languages/"
    dest: /usr/share/phpMyAdmin
    remote_src: yes
    mode: 0750
    owner: nginx
    group: nginx
  
- name: Create additional directories
  file:
    path: "/var/lib/phpMyAdmin/{{ item }}"
    state: directory
    mode: 0770 
    owner: nginx
    group: nginx
  loop:
    - upload
    - save
    - temp
      #    - '../../../etc/phpMyAdmin'

- name: Setuping phpMyAdmin config
  template:
    src: config.inc.php.j2
    dest: /usr/share/phpMyAdmin/config.inc.php
      #dest: /etc/phpMyAdmin/config.inc.php
    mode: 0640
    owner: nginx
    group: nginx

- name: Installing nginx pma config
  template:
    src: phpmyadmin.conf.j2
    dest: /etc/nginx/vhosts/phpmyadmin.conf
    mode: 0644
    owner: root
    group: root 

- name: Setup basic auth file
  htpasswd:
    create: yes
    path: /etc/nginx/conf.d/auth_pma
    name: support
    password: "support_{{ site_name }}"
    state: present
  register: auth_pma

- name: Reload nginx service to apply pma settings
  command: nginx -s reload
  changed_when: false
  when: auth_pma.changed
