- name: Installing Remo repo 
  command: dnf install -y https://rpms.remirepo.net/enterprise/remi-release-8.rpm
  args:  
    warn: no
    creates: /etc/yum.repos.d/remi-safe.repo


- import_tasks: clean_php.yml
  when: reinstall_php | default('false')


- name: Installing System PHP
  dnf:
    name: "{{ php_packages }}"
    enablerepo: "php:remi-{{ system_php }}"
    state: latest

- import_tasks: php-fpm.yml

- include_tasks: secondary_php-fpm.yml
  loop: "{{ secondary_php }}"  
  loop_control:
    loop_var: php
  when: install_secondary_php
